### ISSUE TITLE
Make Credentials uncommitable

### ISSUE THREAD

**Issue by Husterknupp** [Husterknupp/jubilant-todo-tribble#12]
Currently git does not ignore the credentials class which is pretty annoying for every commit

Let's read a Credentials file or our already exisiting application.yaml even for the tests.

**Comment by Husterknupp** [comment]
`mvn integration-test` apparently fails. Was running earlier though. Don't know what changed

```
kotlin.UninitializedPropertyAccessException: lateinit property username has not been initialized
	at de.husterknupp.todoapp.configuration.JiraConfiguration.getUsername(PropertiesConfiguration.kt:37)
	at de.husterknupp.todoapp.JiraHandler.createJiraIssue(JiraHandler.kt:21)
	at de.husterknupp.todoapp.JiraHandler.createJiraIssue$default(JiraHandler.kt:20)
	at de.husterknupp.todoapp.JiraHandlerIT.createJiraIssue(JiraHandlerIT.kt:25)
```

**Comment by Husterknupp** [comment]
http://stackoverflow.com/questions/40410498/spring-test-not-populating-database-configuration-from-application-properties?noredirect=1&lq=1

http://stackoverflow.com/questions/27390085/spring-boot-read-yml-properties-via-integration-test-case

**Comment by Husterknupp** [comment]
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html

 spring boot test autoconfigure might be missing

**Comment by Husterknupp** [comment]
`spring-boot-test-autoconfigure` doesn't make any difference

**Comment by Husterknupp** [comment]
not beautiful but it works 👍
